#!/bin/sh
set +x
root=$(pwd)
outdir="$root/dist"
main="$root/snake.c"
objname="snake"
exec_file=$outdir/$objname
release_opts="-O3 -DNGEBUG -Wall"
opts="-g -Wall"

if [ "$1" = "--release" ] && [ -e "$exec_file" ] ; then
  opts=$release_opts
  outdir="$outdir/release"
fi

# make build dir if not exists
[ ! -d $outdir ] && mkdir -p $outdir


# copy assets
cp $root/SDL2/bin/*.dll $outdir
cp -r $root/assets $outdir

pushd $outdir> /dev/null
[ -e "./$objname" ] && mv "./$objname" "./$objname~"
# build binary
g++ $main $opts \
  -I$root/SDL2/include/SDL2 \
  -L$root/SDL2/lib \
  -L$root/SDL2/bin/SDL2 \
  -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf \
  -w -Wl,-subsystem,windows \
  -o $objname
popd > /dev/null

if [ "$1" = "--run" ] && [ -e "$exec_file" ] ; then
    exec $exec_file
fi

